<?xml version="1.0"?>
<package format="2">
  <name>sensor_fusion</name>
  <version>0.0.1</version>
  <description>GPS + odom EKF fuser that publishes map-frame odometry.</description>

  <maintainer email="iris@todo.todo">iris</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <!-- ROS runtime/build deps actually used by the node -->
  <depend>roscpp</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  

  <!-- System deps resolved by rosdep -->
  <build_depend>eigen</build_depend>           <!-- maps to libeigen3-dev -->
  <build_export_depend>eigen</build_export_depend>
  <exec_depend>eigen</exec_depend>

  <build_depend>geographiclib</build_depend>
  <build_export_depend>geographiclib</build_export_depend>
  <build_depend>geographiclib-tools</build_depend>
  <build_export_depend>geographiclib-tools</build_export_depend>
  
  <export/>
</package>
